/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Ticket } from './types';

export const AREAS_OF_INTEREST = [
  'Trade & AfCFTA',
  'AI, Technology & Innovation',
  'Investment & Fintech',
  'Infrastructure & Industrialization',
  'Green Growth & Climate Finance',
  'Agribusiness & Food Security',
  'Entrepreneurship & SMEs'
];

export const PARTICIPATION_OPPORTUNITIES = [
  { id: 'speaking', label: 'Speaking Opportunity' },
  { id: 'sponsorship', label: 'Sponsorship' },
  { id: 'exhibition', label: 'Exhibition Booth' },
  { id: 'startup', label: 'Startup Showcase' },
  { id: 'networking', label: 'B2B Networking' },
  { id: 'partnership', label: 'Strategic Partnerships' }
];

export const COUNTRIES = [
  { code: 'KE', name: 'Kenya' },
  { code: 'US', name: 'United States' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'GH', name: 'Ghana' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'UG', name: 'Uganda' },
  { code: 'ET', name: 'Ethiopia' },
  { code: 'DE', name: 'Germany' },
  { code: 'FR', name: 'France' },
  { code: 'CA', name: 'Canada' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'IN', name: 'India' },
  { code: 'CN', name: 'China' },
  { code: 'AU', name: 'Australia' }
];

export const GLOBAL_COUNTRY_MAP: { [key: string]: string } = {
  'afghanistan': 'AF',
  'aland islands': 'AX',
  'albania': 'AL',
  'algeria': 'DZ',
  'american samoa': 'AS',
  'andorra': 'AD',
  'angola': 'AO',
  'anguilla': 'AI',
  'antarctica': 'AQ',
  'antigua and barbuda': 'AG',
  'argentina': 'AR',
  'armenia': 'AM',
  'aruba': 'AW',
  'australia': 'AU',
  'austria': 'AT',
  'azerbaijan': 'AZ',
  'bahamas': 'BS',
  'bahrain': 'BH',
  'bangladesh': 'BD',
  'barbados': 'BB',
  'belarus': 'BY',
  'belgium': 'BE',
  'belize': 'BZ',
  'benin': 'BJ',
  'bermuda': 'BM',
  'bhutan': 'BT',
  'bolivia': 'BO',
  'bosnia and herzegovina': 'BA',
  'botswana': 'BW',
  'brazil': 'BR',
  'british indian ocean territory': 'IO',
  'brunei': 'BN',
  'bulgaria': 'BG',
  'burkina faso': 'BF',
  'burundi': 'BI',
  'cambodia': 'KH',
  'cameroon': 'CM',
  'canada': 'CA',
  'cape verde': 'CV',
  'cayman islands': 'KY',
  'central african republic': 'CF',
  'chad': 'TD',
  'chile': 'CL',
  'china': 'CN',
  'christmas island': 'CX',
  'cocos islands': 'CC',
  'colombia': 'CO',
  'comoros': 'KM',
  'congo': 'CG',
  'dr congo': 'CD',
  'democratic republic of congo': 'CD',
  'cook islands': 'CK',
  'costa rica': 'CR',
  'ivory coast': 'CI',
  'cote d\'ivoire': 'CI',
  'croatia': 'HR',
  'cuba': 'CU',
  'cyprus': 'CY',
  'czech republic': 'CZ',
  'czechia': 'CZ',
  'denmark': 'DK',
  'djibouti': 'DJ',
  'dominica': 'DM',
  'dominican republic': 'DO',
  'ecuador': 'EC',
  'egypt': 'EG',
  'el salvador': 'SV',
  'equatorial guinea': 'GQ',
  'eritrea': 'ER',
  'estonia': 'EE',
  'eswatini': 'SZ',
  'swaziland': 'SZ',
  'ethiopia': 'ET',
  'falkland islands': 'FK',
  'faroe islands': 'FO',
  'fiji': 'FJ',
  'finland': 'FI',
  'france': 'FR',
  'french guiana': 'GF',
  'french polynesia': 'PF',
  'gabon': 'GA',
  'gambia': 'GM',
  'georgia': 'GE',
  'germany': 'DE',
  'ghana': 'GH',
  'gibraltar': 'GI',
  'greece': 'GR',
  'greenland': 'GL',
  'grenada': 'GD',
  'guadeloupe': 'GP',
  'guam': 'GU',
  'guatemala': 'GT',
  'guernsey': 'GG',
  'guinea': 'GN',
  'guinea-bissau': 'GW',
  'guyana': 'GY',
  'haiti': 'HT',
  'honduras': 'HN',
  'hong kong': 'HK',
  'hungary': 'HU',
  'iceland': 'IS',
  'india': 'IN',
  'indonesia': 'ID',
  'iran': 'IR',
  'iraq': 'IQ',
  'ireland': 'IE',
  'isle of man': 'IM',
  'israel': 'IL',
  'italy': 'IT',
  'jamaica': 'JM',
  'japan': 'JP',
  'jersey': 'JE',
  'jordan': 'JO',
  'kazakhstan': 'KZ',
  'kenya': 'KE',
  'kiribati': 'KI',
  'north korea': 'KP',
  'south korea': 'KR',
  'korea': 'KR',
  'kuwait': 'KW',
  'kyrgyzstan': 'KG',
  'laos': 'LA',
  'latvia': 'LV',
  'lebanon': 'LB',
  'lesotho': 'LS',
  'liberia': 'LR',
  'libya': 'LY',
  'liechtenstein': 'LI',
  'lithuania': 'LT',
  'luxembourg': 'LU',
  'macao': 'MO',
  'macau': 'MO',
  'madagascar': 'MG',
  'malawi': 'MW',
  'malaysia': 'MY',
  'maldives': 'MV',
  'mali': 'ML',
  'malta': 'MT',
  'marshall islands': 'MH',
  'martinique': 'MQ',
  'mauritania': 'MR',
  'mauritius': 'MU',
  'mayotte': 'YT',
  'mexico': 'MX',
  'micronesia': 'FM',
  'moldova': 'MD',
  'monaco': 'MC',
  'mongolia': 'MN',
  'montenegro': 'ME',
  'montserrat': 'MS',
  'morocco': 'MA',
  'mozambique': 'MZ',
  'myanmar': 'MM',
  'burma': 'MM',
  'namibia': 'NA',
  'nauru': 'NR',
  'nepal': 'NP',
  'netherlands': 'NL',
  'new caledonia': 'NC',
  'new zealand': 'NZ',
  'nicaragua': 'NI',
  'niger': 'NE',
  'nigeria': 'NG',
  'niue': 'NU',
  'norfolk island': 'NF',
  'northern mariana islands': 'MP',
  'norway': 'NO',
  'oman': 'OM',
  'pakistan': 'PK',
  'palau': 'PW',
  'palestine': 'PS',
  'panama': 'PA',
  'papua new guinea': 'PG',
  'paraguay': 'PY',
  'peru': 'PE',
  'philippines': 'PH',
  'pitcairn': 'PN',
  'poland': 'PL',
  'portugal': 'PT',
  'puerto rico': 'PR',
  'qatar': 'QA',
  'reunion': 'RE',
  'romania': 'RO',
  'russia': 'RU',
  'rwanda': 'RW',
  'samoa': 'WS',
  'san marino': 'SM',
  'sao tome and principe': 'ST',
  'saudi arabia': 'SA',
  'senegal': 'SN',
  'serbia': 'RS',
  'seychelles': 'SC',
  'sierra leone': 'SL',
  'singapore': 'SG',
  'slovakia': 'SK',
  'slovenia': 'SI',
  'solomon islands': 'SB',
  'somalia': 'SO',
  'south africa': 'ZA',
  'south sudan': 'SS',
  'spain': 'ES',
  'sri lanka': 'LK',
  'sudan': 'SD',
  'suriname': 'SR',
  'sweden': 'SE',
  'switzerland': 'CH',
  'syria': 'SY',
  'taiwan': 'TW',
  'tajikistan': 'TJ',
  'tanzania': 'TZ',
  'thailand': 'TH',
  'timor-leste': 'TL',
  'east timor': 'TL',
  'togo': 'TG',
  'tokelau': 'TK',
  'tonga': 'TO',
  'trinidad and tobago': 'TT',
  'tunisia': 'TN',
  'turkey': 'TR',
  'turkiye': 'TR',
  'turkmenistan': 'TM',
  'turks and caicos islands': 'TC',
  'tuvalu': 'TV',
  'uganda': 'UG',
  'ukraine': 'UA',
  'united arab emirates': 'AE',
  'uae': 'AE',
  'united kingdom': 'GB',
  'uk': 'GB',
  'great britain': 'GB',
  'united states': 'US',
  'usa': 'US',
  'united states of america': 'US',
  'uruguay': 'UY',
  'uzbekistan': 'UZ',
  'vanuatu': 'VU',
  'vatican city': 'VA',
  'venezuela': 'VE',
  'vietnam': 'VN',
  'viet nam': 'VN',
  'british virgin islands': 'VG',
  'us virgin islands': 'VI',
  'wallis and futuna': 'WF',
  'western sahara': 'EH',
  'yemen': 'YE',
  'zambia': 'ZM',
  'zimbabwe': 'ZW'
};

export const TICKETS: Ticket[] = [
  {
    id: 'early_bird',
    name: 'Early Bird Ticket',
    price: 1500,
    currency: 'KES',
    description: 'Special early access pass for individuals joining within the promotional period.',
    badgeType: ['Delegate']
  },
  {
    id: 'advanced_ind',
    name: 'Advanced Individual Ticket',
    price: 2500,
    currency: 'KES',
    description: 'Standard admission for general participants and business delegates.',
    badgeType: ['Delegate']
  },
  {
    id: 'group_5',
    name: 'Group of 5 Package',
    price: 10000,
    currency: 'KES',
    description: 'Bundle pass for 5 delegates from the same organization. Save KES 2,500 total.',
    badgeType: ['Delegate']
  },
  {
    id: 'corporate',
    name: 'Corporate Pass',
    price: 5000,
    currency: 'KES',
    description: 'Executive tier access with specialized networking area access and certificate.',
    badgeType: ['Delegate', 'Speaker']
  },
  {
    id: 'exhibition_vendor',
    name: 'Exhibition & Vendor Booth',
    price: 100000,
    currency: 'KES',
    description: 'Full custom booth setup within secondary exhibitor hall, including 2 exhibitor entries.',
    badgeType: ['Exhibitor']
  },
  {
    id: 'brand_activation',
    name: 'Brand Activation Ticket',
    price: 200000,
    currency: 'KES',
    description: 'Prominent marketing slots, custom presentation opportunities, and branding space.',
    badgeType: ['Exhibitor', 'Sponsor']
  },
  {
    id: 'title_sponsor',
    name: 'Title Sponsorship Package',
    price: 100000,
    currency: 'USD',
    description: 'Top-tier event alignment. Ultimate logos, 15 VIP tickets, premium custom banners, and opening address privilege.',
    badgeType: ['Sponsor']
  },
  {
    id: 'presenting_sponsor',
    name: 'Presenting Sponsorship',
    price: 50000,
    currency: 'USD',
    description: 'High visibility key partner branding, 10 VIP passes, and custom speaking session rights.',
    badgeType: ['Sponsor']
  },
  {
    id: 'partnering_sponsor',
    name: 'Partnering Sponsorship',
    price: 40000,
    currency: 'USD',
    description: 'Official category sponsor branding, 8 conference passes, and dedicated workshop panel placement.',
    badgeType: ['Sponsor']
  },
  {
    id: 'associate_sponsor',
    name: 'Associate Sponsorship',
    price: 30000,
    currency: 'USD',
    description: 'Co-branding support options, 5 conference passes, and logos on all official documentation physical programs.',
    badgeType: ['Sponsor']
  },
  {
    id: 'supporting_sponsor',
    name: 'Supporting Sponsorship',
    price: 20000,
    currency: 'USD',
    description: 'Standard sponsorship exposure, 3 conference passes, and custom media-pack distribution mentions.',
    badgeType: ['Sponsor']
  }
];
